---
# tasks file for roles/rhel-prepatch
- name: Set CR no for workflow
  set_stats:
    data:
      cr_no: "{{ u_{{ quarter }}_change_request }}"
#  when: u_{{ quarter }}_change_request is defined

- name: Set time for workflow
  set_stats:
    data:
      cr_date: "{{ u_{{ quarter }}_date }}"
#  when: u_{{ quarter }}_date is defined

-  name: print CR no
   debug:
     var: "{{ u_{{ quarter }}_change_request }}"

- name: Check if apps are sotpped or not
  find:
    paths: /var/tmp
    pattern: 'app-stopped'
    age: -24h
  register: app_result

- name: Print if apps are stopped or not
  debug:
    var: app_result.matched
  failed_when: app_result.files | length < 1 

- name: check free disk space
  shell: 'df {{ item }}'
  with_items:
    - "{{ mount_points }}"
  register: df_output
  failed_when: df_output.stdout.split()[11] | regex_replace('%','') | int > 75

- name: running prepatch info commands
  shell: |
    uname -a
    uptime
    date
    adinfo
    cat /etc/resolv.conf
    df -hTP
    df -hP |wc -l
    cat /etc/fstab
    ifconfig -a
    netstat -rn
    vgdisplay
    pvdisplay
    lvscan
    multipath -ll
    blkid
  register: prepatch
  ignore_errors: true

- name: Find files in /etc/yum.repos.d/
  find:
    paths: /etc/yum.repos.d/
    patterns: "*"
  register: files_to_delete

- name: Clean /etc/yum.repos.d/
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_delete.files }}"

- name: Run yum clean all
  command: yum clean all

- name: Get packages that can be patched with security fixes
  yum:
    security: "{{ ev_security_only }}"
    list: updates
    state: latest
    update_cache: yes
  register: reg_dnf_output_secu
 
- name: List packages that can be patched with security fixes
  debug: 
    msg: "{{ reg_dnf_output_secu.results | map(attribute='name') | list }}"
