---
# tasks file for roles/rhel-prepatch
- name: Set CR no for workflow
  set_stats:
    data:
      cr_no: "{{ u_q2_change_request }}"
  when: u_q2_change_request is defined

- name: test msg
  debug:
    msg: pre-patching roles

- name: Check if apps are sotpped or not
  find:
    paths: /var/tmp
    pattern: 'app-stopped'
    age: -24h
  register: app_result

- name: print if apps are stopped or not
  debug:
    var: app_result.matched
  failed_when: app_result.files | length < 1 
#   when: app-stopped.files | length > 0 

- name: check free disk space
  shell: 'df {{ item }}'
  with_items:
    - "{{ mount_points }}"
  register: df_output
  failed_when: df_output.stdout.split()[11] | regex_replace('%','') | int > 70

- name: Distribution version
  debug: 
    msg: "{{ ansible_distribution_version}}"

- name: OS information
  debug:
    msg:  OS. {{ ansible_os_family }} '\n' Hostname. {{ ansible_nodename }} Kernel. {{ ansible_kernel }} and Version. {{ ansible_kernel_version }}

- name: Get packages that can be patched with security fixes
  yum:
    security: "{{ ev_security_only }}"
    list: updates
    state: latest
    update_cache: yes
  register: reg_dnf_output_secu
#  when:  ev_security_only == "yes"
 
- name: List packages that can be patched with security fixes
  debug: 
    msg: "{{ reg_dnf_output_secu.results | map(attribute='name') | list }}"
#  when: ev_security_only == "yes"
