---
# tasks file for roles/rhel-prepatch
- name: test msg
  debug:
    msg: pre-patching roles

- name: check free disk space
  shell: 'df {{ item }}'
  with_items:
    - "{{ mount_points }}"
  register: df_output
  failed_when: df_output.stdout.split()[11] | regex_replace('%','') | int > 70

- name: check df output
  debug:
    msg: "{{ df_output }}"

- name: Distribution version
  debug: 
    msg: "{{ ansible_distribution_version}}"

- name: OS information
  debug:
    msg:  OS. {{ ansible_os_family }} '\n' Hostname. {{ ansible_nodename }} Kernel. {{ ansible_kernel }} and Version. {{ ansible_kernel_version }}

- name: Get packages that can be patched with security fixes
  yum:
    security: "{{ ev_security_only }}"
    list: updates
    state: latest
    update_cache: yes
  register: reg_dnf_output_secu
#  when:  ev_security_only == "yes"
 
- name: List packages that can be patched with security fixes
  debug: 
    msg: "{{ reg_dnf_output_secu.results | map(attribute='name') | list }}"
#  when: ev_security_only == "yes"
