---
# tasks file for roles/rhel-patch

- name: Patch packages
  yum:
    name: '*'
    security: "{{ ev_security_only }}"
    state: latest
    update_cache: yes
  register: reg_upgrade_ok
#  when: ev_security_only == "yes" and reg_dnf_output_secu is defined
  tags:
    - update
 
- name: Print errors if upgrade failed
  ansible.builtin.debug:
    msg: "Packages upgrade failed"
  when: reg_upgrade_ok is not defined
- name: Check if a reboot is required
  become: yes
  command: needs-restarting -r
  register: reg_reboot_required
  ignore_errors: yes
  failed_when: false
  changed_when: reg_reboot_required.rc != 0
  notify:
    - Reboot server 
