---
# tasks file for roles/rhel-patch

- name: Patch packages
  yum:
    name: '*'
    security: "{{ ev_security_only }}"
    state: latest
    update_cache: yes
  register: reg_upgrade_ok
  when: ansible_distribution == "RedHat"
  tags:
    - update

- name: Print output of patching results
  debug:
    var: reg_upgrade_ok.results

- name: "Artifact results to Tower Workflows"
  set_stats:
    data:
      patching_ok:  "{{ reg_upgrade_ok.results }}"

#- name: Set CR no for workflow
#  set_stats:
#    data:
#      cr_no: "{{ u_q2_change_request }}" 
 
- name: Print errors if upgrade failed
  debug:
    msg: "Packages upgrade failed"
  when: reg_upgrade_ok is not defined

- name: Check if a reboot is required
  become: yes
  command: needs-restarting -r
  register: reg_reboot_required
  ignore_errors: yes
  failed_when: false
  changed_when: reg_reboot_required.rc != 0
  notify:
    - Reboot server 
