---
plugin: servicenow.itsm.now
table: cmdb_ci_linux_server
ansible_host_source: host_name
inventory_hostname_source: host_name
columns:
  - host_name
  - os 
  - location
group_by:
  install_status:
    includes:
      - 1
  os:
    includes:
      -  RedHatEnterpriseServer
      -  Linux Red Hat
