---
# handlers file for linux-config
- name: Restart chrony
  service:
    name: chronyd
    state: restarted

- name: Restart ntp
  service:
    name: ntpd
    state: restarted

- name: Restart sendmail
  service:
    name: sendmail
    state: restarted

- name: Restart postfix
  service:
    name: postfix
    state: restarted
