---
- name: RHEL OS Patching
  hosts: all
  gather_facts: yes
  vars:
    ev_security_only: no
    quarter: "{{ qrt | default('q3') }}"
  roles:
    - rhel-prepatch
    - rhel-patch
    - rhel-postpatch 
