---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: include vars
    include_vars: change_request_vars.yml

  - name: Create a incident request
    snow_record:
      instance: "{{ sn_instance }}"
      state: present
      table: incident
      data:
        severity: "{{ sn_severity }}"
        priority: "{{ sn_priority }}"
        short_description: "{{ cr_no }} implementation failed"
        assignment_group: "{{ assignment_group }}"
        cmdb_ci: "unix"
        rfc: "{{ cr_no }}"
    register: new_incident

  - name: Print incident number
    debug:
      var: new_incident.record.number
