---
- name: Create ticket with notes
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: include vars
    include_vars: change_request_vars.yml
  
#  - name: print cr no
#    debug:
#      var: "{{ cr_no }}"

  - name: "Modify a change request {{ cr_no }}"
    snow_record:
      state: present
      table: change_request
#      username: "{{ sn_username }}"
#      password: "{{ sn_password }}"
      instance: "{{ sn_instance }}"
      number: "{{ cr_no }}"
      data:
#      record:
        state: 3
#        close_code: "Successful"
#        close_notes: "{{ patching_ok }}"
        u_implementation_status: "successful"
        work_start: "{{ cr_date }}"
        work_end: "{{ansible_date_time.date}} {{ansible_date_time.time}}"
        u_validation_details: "{{ patching_ok }}"
        u_cause_incident: "No"
        u_remediation_required: "Not Required"
        u_cmdb_updated: "No"
    register: change

#  - name: Print change state 
#    debug:
#      var: change
#      var: change.record.state

