- name: cleanup
  hosts: rhel7
  tasks:
#    - name: cleanup repo dir
#      file:
#        state: absent
#        path: /etc/yum.repos.d/*.repo

  - name: Ansible delete file glob
    find:
      paths: /etc/yum.repos.d/
      patterns: "*"
    register: files_to_delete

  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
